# Generated by Django 5.2.1 on 2025-06-02 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tecnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('image_tecnology', models.ImageField(blank=True, null=True, upload_to='media/technologies')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image_project', models.ImageField(blank=True, null=True, upload_to='media/projects')),
                ('technologies', models.ManyToManyField(related_name='projects', to='projects.tecnology')),
            ],
        ),
    ]
