# Generated by Django 5.2.1 on 2025-06-03 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_technology_delete_tecnology_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='technology',
            old_name='image_tecnology',
            new_name='image_technology',
        ),
    ]
