# Generated by Django 5.2.1 on 2025-06-04 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_image_tecnology_technology_image_technology'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_project',
            field=models.ImageField(blank=True, null=True, upload_to='projects'),
        ),
    ]
