# Generated by Django 5.2.1 on 2025-06-23 22:53

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_contactme_alter_userprofile_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactme',
            name='user_message',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Message'),
        ),
        migrations.CreateModel(
            name='AboutPageConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('featured_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
